[package]
name = "engipay-api"
description = "EngiPay HTTP API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
engipay-core.workspace = true
engipay-ledger = { workspace = true, features = ["postgres"] }
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
jsonwebtoken.workspace = true
ed25519-dalek.workspace = true
stellar-strkey.workspace = true
stellar-xdr.workspace = true
sha2.workspace = true
sha3.workspace = true
k256.workspace = true
hex.workspace = true
rand.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"

[lints]
workspace = true
